pipeline {
    agent any
    environment {
        CI = 'false'
        DOCKER_IMAGE = 'hajewoong/qt-sqace-backend'
        PATH = "$PATH:$HOME/bin"
        JAVA_HOME="/usr/lib/jvm/java-17-openjdk-17.0.13.0.11-3.0.1.el8.x86_64"
    }
    stages {
        stage('test gateway') {
            steps {
                sh '''
                cd gateway
                ./gradlew :test
                '''
            }
        }
        stage('build docker image') {
            steps {
                sh '''
                cd gateway
                docker build -t ${DOCKER_IMAGE}-gateway:latest .
                '''
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                    sh 'docker push ${DOCKER_IMAGE}-gateway:latest'
                }
            }
        }
        stage('deploy') {
            steps {
                sh 'kubectl rollout restart deployment/gateway -n spring-boot-app '
            }
        }
    }
    post {
        always {
            sh 'docker rmi -f $(docker images -q)'
        }
    }
}
