pipeline {
    agent any
    environment {
        CI = 'false'
        DOCKER_IMAGE = 'hajewoong/qt-sqace-backend'
    }
    stages {
        stage('test gateway') {
            steps {
                sh '''
                cd gateway
                ./gradlew test
                '''
            }
        }
        stage('build docker image'){
            steps{
                sh '''
                cd gateway
                docker build -t ${DOCKER_IMAGE}-gateway:latest .
                '''
            }
        }
    }
    post{
        always{
            sh 'docker image prune -f'
        }   
    }
}
