server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: aiservice
          uri: http://aiservice.spring-boot-app.svc.cluster.local:8082
          predicates:
            - Path=/aiservice/**
          filters:
            - RewritePath=/aiservice/(?<segment>.*), /$\{segment}

        - id: userservice
          uri: http://userservice.spring-boot-app.svc.cluster.local:8080
          predicates:
            - Path=/userservice/**
          filters:
            - RewritePath=/userservice/(?<segment>.*), /$\{segment}

        - id: teamservice
          uri: http://teamservice.spring-boot-app.svc.cluster.local:8081
          predicates:
            - Path=/teamservice/**
          filters:
            - RewritePath=/teamservice/(?<segment>.*), /$\{segment}

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

logging:
  level:
    org.springframework: DEBUG

secret- key: "ThisStatementIsJwtSecretKeyDoNotUseThisStatement"
