server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: aiservice
          uri: lb://AI-SERVICE
          predicates:
            - Path=/aiservice/**
          filters:
            - RewritePath=/aiservice/(?<segment>.*), /$\{segment}
            - name: JwtAuthenticationFilter #필터 적용

        - id: userservice
          uri: lb://USER-SERVICE
          predicates:
            - Path=/userservice/**
          filters:
            - RewritePath=/userservice/(?<segment>.*), /$\{segment}

        - id: teamservice
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/teamservice/**
          filters:
            - RewritePath=/teamservice/(?<segment>.*), /$\{segment}

        - id: calendarservice
          uri: lb://CALENDAR-SERVICE
          predicates:
            - Path=/calendarservice/**
          filters:
            - RewritePath=/calendarservice/(?<segment>.*), /$\{segment}

        - id: chatservice
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chatservice/**
          filters:
            - RewritePath=/chatservice/(?<segment>.*), /$\{segment}

#        # WebSocket 요청 처리
#        - id: chatservice-websocket
#          uri: lb://CHAT-SERVICE
#          predicates:
#            - Path=/chatservice/ws # WebSocket 요청 경로
#          filters:
#            - RewritePath=/chatservice/ws, /ws # 경로 재작성

      # Global CORS 설정
      globalcors:
        corsConfigurations:
          '[/**]':  # 모든 경로에 대해 CORS 설정 적용
            allowedOrigins:
              - "http://localhost:3000"
              - "https://jiangxy.github.io" # stomp웹사이트 테스트 도메인
              - "https://www.toolfk.com" # 추후에는 이런식으로 배포 도메인 사용
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - "*"
            allowCredentials: true  # 인증 정보 포함
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
logging:
  level:
    org.springframework: DEBUG

secret-key: "ThisStatementIsJwtSecretKeyDoNotUseThisStatement"
