apiVersion: v1
kind: Namespace
metadata:
  name: spring-boot-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: hajewoong/qt-sqace-backend-gateway:latest
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: spring-boot-app
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: spring-boot-app
spec:
  rules:
    - host: api.sqace.site  # 서브도메인 설정
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway  # 게이트웨이 서비스 이름
                port:
                  number: 8000  # 게이트웨이 서비스 포트
