apiVersion: v1
kind: Namespace
metadata:
  name: spring-boot-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: hajewoong/qt-sqace-backend-gateway:latest
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: spring-boot-app
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: spring-boot-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2  # 재작성 규칙 설정
    nginx.ingress.kubernetes.io/use-regex: "true"   # 정규식을 사용
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: gateway  # React 앱 서비스 이름
                port:
                  number: 8000

