apiVersion: v1
kind: Namespace
metadata:
  name: spring-boot-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: hajewoong/qt-sqace-backend-chat-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: spring-boot-app
spec:
  type: ClusterIP
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
