pipeline {
    agent any
    environment {
        CI = 'false'
        DOCKER_IMAGE = 'hajewoong/qt-sqace-backend'
        PATH = "$PATH:$HOME/bin"
    }
    stages {
        stage('build docker image') {
            steps {
                sh '''
                cd chat-service
                docker build -t ${DOCKER_IMAGE}-chat-service:latest .
                '''
            }
        }
        stage('Push Docker Image'){
            steps{
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                    sh 'docker push ${DOCKER_IMAGE}-chat-service:latest'
                }
            }
        }
        stage('deploy') {
            steps {
                sh 'kubectl apply -f chat-service/src/main/k8s/k8s.yaml'
                sh 'kubectl rollout restart deployment/chat-service -n spring-boot-app'
            }
        }
    }
    post{
        always{
            sh 'docker rmi -f $(docker images -q)'
        }
    }
}