apiVersion: v1
kind: Namespace
metadata:
  name: spring-boot-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-service
  namespace: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-service
  template:
    metadata:
      labels:
        app: team-service
    spec:
      containers:
        - name: team-service
          image: hajewoong/qt-sqace-backend-team-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: team-service
  namespace: spring-boot-app
spec:
  type: ClusterIP
  selector:
    app: team-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081