apiVersion: v1
kind: Namespace
metadata:
  name: spring-boot-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-service
  namespace: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-service
  template:
    metadata:
      labels:
        app: calendar-service
    spec:
      containers:
        - name: calendar-service
          image: hajewoong/qt-sqace-backend-calendar-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "8084"
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-service
  namespace: spring-boot-app
spec:
  type: ClusterIP
  selector:
    app: calendar-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
