apiVersion: v1
kind: Namespace
metadata:
  name: spring-boot-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calender-service
  namespace: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calender-service
  template:
    metadata:
      labels:
        app: calender-service
    spec:
      containers:
        - name: calender-service
          image: hajewoong/qt-sqace-backend-calender-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "8084"
---
apiVersion: v1
kind: Service
metadata:
  name: calender-service
  namespace: spring-boot-app
spec:
  type: ClusterIP
  selector:
    app: calender-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
